## Getting started

In [1]:
from __future__ import annotations

import random
import math
import time
from typing import Tuple, Optional, Union, NamedTuple, Callable
import itertools
import functools

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

## jnumpy

In [15]:
# Jnumpy: Jacob's numpy library for machine learning
# Copyright (c) 2021 Jacob F. Valdez. Released under the MIT license.


V = np.array # V is for Value type
Vs = Tuple[V]
Vss = Union[V,Vs]


class ExecutionMode:
    EAGER=1
    STATIC=2  # STATIC execution mode not supported
    
EXECUTION_MODE = ExecutionMode.EAGER


class T:
    """Tensor"""
    
    def __init__(self, val: Optional[V] = None):
        self.val = val
        
        if val is None:
            raise 'STATIC execution mode not supported'
    
    def __add__(self, other):
        return eval("Add")(self, other)
    
    def __neg__(self):
        return eval('Neg')(self)
    
    def __sub__(self, other):
        return eval("Sub")(self, other)
    
    def __mul__(self, other):
        return eval("Mul")(self, other)
    
    def __pow__(self, other):
        return eval("Pow")(self, other)
    
    def __matmul__(self, other):
        return eval("MatMul")(self, other)

    def __getitem__(self, key):
        return eval("Index")(self, key)

    def __setitem__(self, key, value):
        raise NotImplementedError('slice assign not yet supported')

    @property
    def shape(self):
        return self.val.shape

    @property
    def ndim(self):
        return self.val.ndim

    @property
    def size(self):
        return self.val.size

    @property
    def dtype(self):
        return self.val.dtype

    @property
    def T(self, axes: Optional[Tuple[int]] = None):
        return eval("Transpose")(self, axes=axes)

    def __repr__(self):
        return f"Tensor({self.val})"

    def __str__(self):
        return f"Tensor({self.val})"

    def __eq__(self, other):
        return self.val == other.val

    def __hash__(self):
        return hash(self.val)

    def __iter__(self):
        return iter(self.val)

    def __len__(self):
        return len(self.val)

    def __getstate__(self):
        return self.val.__getstate__()

    def __setstate__(self, state):
        self.val = state

    def __array__(self):
        return self.val.__array__()


Ts = Tuple[T]
Tss = Union[T,Ts]


class Var(T):
    """Variable Tensor"""
    def __init__(self, val: Optional[V] = None, trainable: bool = True):
        
        self.trainable = trainable
        super().__init__(val=val)


class Op(T):
    """Operation-backed Tensor"""
    
    def __init__(self, *inputs: T):
        """Make sure to set any variables you might need in `forward` 
        before initializing when the graph is in eager execution mode
        """
        
        self.input_ts = inputs
        
        if EXECUTION_MODE == ExecutionMode.EAGER:
            val = self.forward(tuple(i.val for i in inputs))[0]
        else:
            val = None
        
        super().__init__(val=val)
        
    def forward(self, inputs: Vs) -> Vs:
        raise NotImplementedError('subclasses should implement this method')
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        raise NotImplementedError('subclasses should implement this method')


class Transpose(Op):
    
    def __init__(self, t: T, axes: Optional[Tuple[int]] = None):
        
        self.forward_kwargs = dict()
        self.reverse_kwargs = dict()
        
        if axes is not None:
            self.forward_kwargs['axes'] = axes
            self.reverse_kwargs['axes'] = tuple(reversed(axes))
            
        super().__init__(t)
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Y = X.transpose(**self.forward_kwargs)
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dY = top_grads[0]
        
        dX = dY.transpose(**self.reverse_kwargs)
        
        return (dX,)


class Reshape(Op):
    
    def __init__(self, t: T, shape: Tuple[int]):
        
        self.reshape_shape = shape
            
        super().__init__(t)
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Y = X.reshape(self.reshape_shape)
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dY = top_grads[0]
        
        dX = dY.reshape(tuple(reversed(self.reshape_shape)))
        
        return (dX,)
 

class Concat(Op):
    
    def __init__(self, ts: list[T], axis: int=0):
        """Concatenates input tensors along an axis

        Args:
            t (T): [description]
            axis (int, optional): Axis to concatenate along. Defaults to 0.
        """
        
        self.axis = axis
        self.orig_axis_lens = [t.shape[axis] for t in ts]

        super().__init__(*ts)
    
    def forward(self, inputs: Vs) -> Vs:
        Xs = inputs
        
        Y = np.concatenate(Xs, axis=self.axis)
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dY = top_grads[0]
        
        dXs = np.split(dY, self.orig_axis_dims, axis=self.axis)[0]
        
        return dXs


class Index(Op):
    
    def __init__(self, t: T, indices):
        """Slices a tensor along all axes.

        Args:
            t (T): The tensor to slice
            indices (Tuple[slice]):  The partial or full indices to slice on `t`.
                Can be an index, single slice, tuple of slices, or Ellipsis.
                `None` is not allowed.
        """
        if not isinstance(indices, tuple):
            indices = (indices,)

        self.indices = indices
        
        super().__init__(t)
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Y = X[self.indices]
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]
        dY = top_grads[0]
        
        dX = np.zeros(X.shape)
        dX[self.indices] = dY
        
        return (dX,)


class ReduceSum(Op):
    
    def __init__(self, t: T, axis: int):
        self.sum_axis = axis
            
        super().__init__(t)
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Y = X.sum(axis=self.sum_axis)
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]
        dY = top_grads[0]
        
        dX = np.repeat(
            np.expand_dims(dY, axis=self.sum_axis),
            X.shape[self.sum_axis],
            axis=self.sum_axis
        )
        
        return (dX,)


class NaN2Num(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = np.nan_to_num(X, posinf=10., neginf=-10.)
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = np.nan_to_num(dZ, posinf=10., neginf=-10.)
        
        return (dX,)


class Linear(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = X
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = dZ
        
        return (dX,)


class StopGrad(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = X
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = np.zeros_like(dZ)
        
        return (dX,)


class Neg(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = -X
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = -dZ
        
        return (dX,)


class Add(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        Y = inputs[1]
        
        Z = X + Y
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = dZ
        dY = dZ
        
        return dX, dY


class Sub(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        Y = inputs[1]
        
        Z = X - Y
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = dZ
        dY = -dZ
        
        return dX, dY


class Mul(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        Y = inputs[1]
        
        Z = X * Y
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]
        Y = inputs[1]
        dZ = top_grads[0]
        
        dX = Y * dZ
        dY = X * dZ
        
        return dX, dY


class MatMul(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        Y = inputs[1]
        
        Z = X @ Y
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]  # [A,B]
        Y = inputs[1]  # [B,C]
        dZ = top_grads[0]  # [A,C]
        
        dX = dZ @ Y.transpose()
        dY = X.transpose() @ dZ
        
        return dX, dY


class Exp(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = np.exp(X)
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        Z = outputs[0]
        dZ = top_grads[0]
        
        dX = Z * dZ
        
        return (dX,)


class Sigm(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = 1 / (1 + np.exp(-X))
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        Z = outputs[0]
        dZ = top_grads[0]
        
        dX = Z * (1 - Z) * dZ
        
        return (dX,)


class Tanh(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = np.tanh(X)
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        Z = outputs[0]
        dZ = top_grads[0]
        
        dX = ((1 - Z)**2) * dZ
        
        return (dX,)


class Relu(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = (X > 0) * X
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]
        dZ = top_grads[0]
        
        dX = (X > 0) * dZ
        
        return (dX,)


class Threshold(Op):
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        
        Z = (X >= 0)
        
        return (Z,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        dZ = top_grads[0]
        
        dX = dZ
        
        return (dX,)


class Pow(Op):
    
    def __init__(self, x: T, power: int):
        
        self.power = power
        
        super().__init__(x)
    
    def forward(self, inputs: Vs) -> Vs:
        X = inputs[0]
        p = self.power
        
        Y = X ** p
        
        return (Y,)
    
    def reverse_grad(self, inputs: Vs, outputs: Vs, top_grads: Vs) -> Vs:
        X = inputs[0]
        p = self.power
        dY = top_grads[0]
        
        dY = p * X ** (p-1) * dY
        dY = np.nan_to_num(dY, posinf=10., neginf=-10.)
        
        return (dY,)


class Optimizer:
    
    def minimize(self, t: T):
        pass


class SGD(Optimizer):
    
    def __init__(self, lr: float = 0.001):
        
        self.lr = lr
        self.debug = False
        
        super().__init__()
    
    def minimize(self, t: T):
        
        if EXECUTION_MODE == ExecutionMode.STATIC:
            raise 'STATIC execution mode not enabled'
        
        self.bprop(t_out=t, output_grad=-np.ones_like(t.val))
        
    def bprop(self, t_out: T, output_grad: V):
        
        output_grad = np.nan_to_num(output_grad, posinf=10., neginf=-10.)
        
        assert isinstance(t_out, (Var, Op))
        
        if self.debug:
            print(f'bp {t_out} output_grads:')
            print(output_grad)
        
        """
        This approach does not efficiently handle weights that are consumed by multiple nodes
        It would be better to treat backpropagation from a spreading-network-delta perspective
        than assume everything is a tree (That's also how I should do STATIC execution refresh)
        This should still work though, but it's just going to set the same weight multiple times
        for every downstream consumer.

        Actually, the whole thesis of minibatch gradient descent is that we can approximate a global
        gradient by updates on local subsets of data, so it might be sufficient to leave the code
        as is.
        """
        
        # iteratively called
        if isinstance(t_out, Var):
            if t_out.trainable:
                #print('output_grad', output_grad.shape)
                if self.debug:                    
                    print('t_out.val (old)', t_out.shape)
                    print(t_out.val)
                
                # yucky duct tape to handle batch size differences
                if t_out.shape[0] == 1 and output_grad.shape[0] > 1:
                    output_grad = np.sum(output_grad, axis=0)[None, ...]

                t_out.val = t_out.val + (self.lr * output_grad)
                if self.debug:
                    print('t_out.val (new)', t_out.shape)
                    print(t_out.val)
            
        elif isinstance(t_out, Op):
            input_grads = t_out.reverse_grad(
                inputs=tuple(t.val for t in t_out.input_ts),
                outputs=(t_out.val,), 
                top_grads=(output_grad,))
            
            for input_t, input_grad in zip(t_out.input_ts, input_grads):
                self.bprop(t_out=input_t, output_grad=input_grad)
        
        return

## Neural Network

In [6]:
class Layer:

    def __init__(self) -> None:
        self._built = False
        self._loss = Var(np.zeros(()), trainable=False)

    @property
    def loss(self) -> T:
        return self._loss

    @property
    def trainable_variables(self) -> list[T]:
        pass

    def build(self, input_shape):
        pass

    def forward(self, X_T: T) -> T:
        pass

    def __call__(self, X_T: T) -> T:
        if not self._built:
            self.build(X_T.shape)
            self._built = True

        # reset the regularization loss
        self._loss = Var(0, trainable=False)

        return self.forward(X_T)

In [7]:
class Dense(Layer):

    def __init__(self, 
        units: int, 
        activation: Op = None, 
        use_bias: bool = True,
        activity_L2: float = None, 
        weight_L2: float = None,  
        bias_L2: float = None
    ):
        super(Dense, self).__init__()

        if activation is None:
            activation = Linear
            
        self.units = units
        self.activation = activation
        self.use_bias = use_bias

        self.activity_L2 = Var(activity_L2, trainable=False) if activity_L2 is not None else None
        self.weight_L2 = Var(weight_L2, trainable=False) if weight_L2 is not None else None
        self.bias_L2 = Var(bias_L2, trainable=False) if bias_L2 is not None else None

    @property
    def trainable_variables(self) -> list[T]:
        return [self.W_T] + ([self.B_T] if self.use_bias else [])

    def build(self, input_shape):
        W = np.random.uniform(low=-0.05, high=0.05, size=(input_shape[-1], self.units))
        self.W_T = Var(val=W, trainable=True)
        if self.use_bias:
            B = np.random.uniform(low=-0.05, high=0.05, size=(1, self.units))
            self.B_T = Var(val=B, trainable=True)

    def forward(self, X_T: T) -> T:

        # compute presynaptic input
        Z_T = X_T @ self.W_T

        # maybe add bias
        if self.use_bias:
            Z_T = Z_T + self.B_T

        # apply activation
        Y_T = self.activation(Z_T)
        
        # track regularization losses
        if self.activity_L2 is not None:
            self._loss += self.activity_L2 * ReduceSum(ReduceSum(Y_T**2, 1), 0)
        if self.weight_L2 is not None:
            self._loss += self.weight_L2 * ReduceSum(ReduceSum(self.W_T**2, 1), 0)
        if self.use_bias and self.bias_L2 is not None:
            self._loss += self.bias_L2 * ReduceSum(ReduceSum(self.B_T**2, 1), 0)

        return Y_T


layer = Dense(10, Relu, 0.1, 0.1, 0.1)
X_T = Var(np.random.uniform(0, 1, size=(3, 5)), trainable=False)
Y_T = layer(X_T)
X_T.val, Y_T.val, layer.loss, layer.trainable_variables

(array([[0.86864566, 0.92713307, 0.89508585, 0.75241702, 0.6668152 ],
        [0.57758617, 0.1520879 , 0.00955446, 0.69276964, 0.02875664],
        [0.22569341, 0.01265441, 0.03056132, 0.74256083, 0.73818295]]),
 array([[-0.        , -0.        , -0.        , -0.        , -0.        ,
          0.10104463, -0.        , -0.        ,  0.04244365,  0.0863988 ],
        [ 0.02917887,  0.0353168 , -0.        , -0.        ,  0.02639938,
          0.05926357,  0.04120708,  0.00860686,  0.03574176,  0.03599362],
        [ 0.05351079,  0.07113467, -0.        , -0.        ,  0.00068787,
          0.01867601,  0.0282362 ,  0.00126863,  0.04392415,  0.02155162]]),
 Tensor(0.007903155590653417),
 [Tensor([[-0.02457278  0.00993248 -0.0021894  -0.01877936  0.02044519  0.04260977
     0.0198656   0.00239152 -0.0216521   0.03488872]
   [-0.03009463 -0.03818426 -0.01805062 -0.02704085 -0.04051698  0.03558481
    -0.00900563  0.02351372  0.02355069  0.04047119]
   [-0.02608792 -0.04711397  0.00038614  0.

In [47]:
class Conv2D(Layer):
    """Standard 2D Conv layer.
    I.E. convolves over Tensors shaped [B, H, W, D]
    to produce [B, H-2*kernel_size, W-2*kernel_size, filters]
    """

    def __init__(self,
        filters: int, 
        kernel_size: Union[int, Tuple[int, int]] = 3,
        strides: Union[int, Tuple[int, int]] = 1,
        padding: str = 'valid',  # 'valid' or 'same'
        activation: Op = None,
        use_bias: bool = False,
        activity_L2: float = None, 
        weight_L2: float = None,  
        bias_L2: float = None,
    ):
        super(Conv2D, self).__init__()

        if activation is None:
            activation = Linear
        if isinstance(kernel_size, int):
            kernel_size = (kernel_size, kernel_size)
        assert kernel_size[0] % 2 == 1 and kernel_size[1] % 2 == 1, 'kernel_size must be odd'
        if isinstance(strides, int):
            strides = (strides, strides)
        assert strides[0] > 0 and strides[1] > 0, 'strides must be positive'
        padding = padding.lower()
        assert padding in ('valid', 'same'), 'padding must be valid or same'

        self.filters = filters
        self.kernel_size = kernel_size
        self.strides = strides
        self.padding = padding
        self.activation = activation
        self.use_bias = use_bias

        self.activity_L2 = Var(activity_L2, trainable=False) if activity_L2 is not None else None
        self.weight_L2 = Var(weight_L2, trainable=False) if weight_L2 is not None else None
        self.bias_L2 = Var(bias_L2, trainable=False) if bias_L2 is not None else None

    @property
    def trainable_variables(self) -> list[T]:
        return [self.W_T] + ([self.B_T] if self.use_bias else [])

    def build(self, input_shape):
        W = np.random.uniform(low=-0.05, high=0.05, size=(
            self.kernel_size[0]*self.kernel_size[1]*input_shape[-1], 
            self.filters))
        self.W_T = Var(val=W, trainable=True)
        
        if self.use_bias:
            B = np.random.uniform(low=-0.05, high=0.05, size=(1, self.filters))
            self.B_T = Var(val=B, trainable=True)

    def forward(self, X_T: T) -> T:

        print('input', X_T.shape)

        # maybe pad input
        if self.padding == 'same':

            # various padding sizes, strides, and offsets
            # 0   1   2   3   4
            #     0 1 2 3 4
            #         0 1 2 3 4 5 6 7 8 9
            #         0 1 2 3 4
            #         0   1   2   3   4

            pad_top = self.strides[0]*(self.kernel_size[0]-1)//2
            pad_bottom = pad_top
            pad_left = self.strides[1]*(self.kernel_size[1]-1)//2
            pad_right = pad_left
            B, H_orig, W_orig, C = X_T.shape

            # pad height
            X_T = Concat([
                Var(np.zeros((B, pad_top, W_orig, C)), trainable=False),
                X_T,
                Var(np.zeros((B, pad_bottom, W_orig, C)), trainable=False),
            ], axis=1)

            # pad width
            X_T = Concat([
                Var(np.zeros((B, H_orig+pad_top+pad_bottom, pad_left, C)), trainable=False),
                X_T,
                Var(np.zeros((B, H_orig+pad_top+pad_bottom, pad_right, C)), trainable=False),
            ], axis=2)

        elif self.padding == 'valid':
            pass

        # stack the input tensor along the channel axis
        # but shifted by all possible kernel shifts

        print('padded', X_T.shape)
        #print((10*X_T[0, :, :, 0].val).astype(int))


        stack = []
        # THIS IS THE WRONG WAY TO DO THIS
        # I SHOULD BE GOING BY KERNEL PIXEL INDICES INSTEAD OF INPUT PIXEL INDICES
        # free_height = X_T.shape[1] - (self.strides[0]*self.kernel_size[0]-1)
        # free_width = X_T.shape[2] - (self.strides[1]*self.kernel_size[1]-1)
# 
        # for shift in itertools.product(range(free_height+1), range(free_width+1)):
        #     start_height, start_width = shift
        #     stack.append(
        #         X_T[:, 
        #             start_height:start_height+self.kernel_size[0],
        #             start_width:start_width+self.kernel_size[1],
        #             :]
        #     )

        for shift in itertools.product(range(0, self.strides[0]*self.kernel_size[0], self.strides[0]),
                                       range(0, self.strides[1]*self.kernel_size[1], self.strides[1])):
            stack.append(X_T[
                :,
                shift[0]:,
                shift[1]:,
                :
            ])
            #     slice(None, None), 
            #     slice(
            #         shift[0],
            #         X_T.shape[1]-(1+self.kernel_size[0]//2)+shift[0], 
            #         self.strides[0]),
            #     slice(
            #         shift[1],
            #         X_T.shape[2]-(1+self.kernel_size[1]//2)+shift[1], 
            #         self.strides[1]),
            #     slice(None, None)
            # ])
            # print(shift, stack[-1].shape)

        # clip stack to same dimensions
        min_shape = np.min(np.array([s.shape for s in stack]), axis=0)
        stack = [s[:, :min_shape[1], :min_shape[2], :] for s in stack]

        # stack the shifted tensors along the channel axis
        stacked = Concat(stack, axis=3)  # [B, H-k_h//2, W-k_w//2, C*k_h*k_w]

        # convolve over the stacked tensors
        Z_T = stacked @ self.W_T  
    
        # maybe add bias
        if self.use_bias:
            Z_T = Z_T + self.B_T

        # apply the activation function
        Y_T = self.activation(Z_T)

        # track regularization losses
        if self.activity_L2 is not None:
            self._loss += self.activity_L2 * ReduceSum(ReduceSum(Y_T**2, 1), 0)
        if self.weight_L2 is not None:
            self._loss += self.weight_L2 * ReduceSum(ReduceSum(self.W_T**2, 1), 0)
        if self.use_bias and self.bias_L2 is not None:
            self._loss += self.bias_L2 * ReduceSum(ReduceSum(self.B_T**2, 1), 0)

        return Y_T


layer = Conv2D(filters=64, kernel_size=5, strides=5, padding='same', weight_L2=0.1)
X_T = Var(np.random.uniform(0, 1, size=(2, 7, 70, 5)), trainable=False)
Y_T = layer(X_T)
X_T.shape, Y_T.shape, layer.loss, layer.trainable_variables

input (2, 7, 70, 5)
padded (2, 27, 90, 5)


((2, 7, 70, 5),
 (2, 7, 70, 64),
 Tensor(0.6655775763224356),
 [Tensor([[ 0.04319845  0.03023083  0.00187009 ... -0.04315947  0.02107388
     0.03148008]
   [ 0.02245594 -0.00383444  0.02949396 ... -0.03407175  0.02240345
     0.04264184]
   [ 0.00967554  0.00856563 -0.01957414 ... -0.04670813  0.01688541
    -0.00793862]
   ...
   [-0.02169781  0.01405197 -0.00351415 ...  0.01277215 -0.01822374
     0.00560085]
   [-0.03846189  0.01834757 -0.01413276 ... -0.04137921 -0.04816662
    -0.00257595]
   [-0.04592661  0.00412942 -0.01291353 ...  0.04912848  0.03650673
    -0.03092112]])])

In [6]:
class Flatten(Layer):
    """Flattens all non-batch dimensions into a single axis"""

    def __init__(self):
        super(Flatten, self).__init__()

    @property
    def trainable_variables(self) -> list[T]:
        return []

    def forward(self, X_T: T) -> T:
        flat_dims = functools.reduce(lambda x, y: x*y, X_T.shape[1:])
        Y_T = Reshape(X_T, (X_T.shape[0], flat_dims))
        return Y_T


layer = Flatten()
X_T = Var(np.random.uniform(0, 1, size=(2, 3, 4, 5)), trainable=False)
Y_T = layer(X_T)
X_T.shape, Y_T.shape, layer.loss, layer.trainable_variables

((2, 3, 4, 5), (2, 60), <__main__.Var at 0x7fb12d828640>, [])

In [7]:
class Sequential(Layer):

    def __init__(self, layers):
        self.layers = layers
        super(Sequential, self).__init__()

    def forward(self, X_T: T) -> T:
        for layer in self.layers:
            X_T = layer(X_T)
        return X_T

    @property
    def loss(self) -> T:
        return sum(layer.loss for layer in self.layers)

    @property
    def trainable_variables(self) -> list[T]:
        trainable_vars = []
        for layer in self.layers:
            trainable_vars += layer.trainable_variables
        return trainable_vars


net = Sequential([
    Dense(10, Relu),
    Dense(128, Relu),
    Dense(512, Sigm),
    Dense(1, lambda x: x)
])
net(X_T)

img_T = Var(np.random.uniform(0, 1, size=(1, 28, 28, 1)), trainable=False)
net = Sequential([
    Conv2D(32, 3, 2, activation=Relu),
    Conv2D(64, 3, 2, activation=Relu),
    Flatten(),
    Dense(512, Sigm),
    Dense(1, lambda x: x)
])
net(img_T)

AxisError: axis 3 is out of bounds for array of dimension 3

## Reinforcement Learning

Standards:
- `Step`: uses batch dimension (except `done` which is always a bool)
- `Agent` uses batch dimension
- `Environment` doesn't use batch dimension

This means you will have to use `Step.batch` and `Step.unbatch` in your training/running loop

In [24]:
class Step(NamedTuple):
    """Single step."""
    
    obs: np.ndarray
    next_obs: np.ndarray
    action: np.ndarray
    reward: np.ndarray
    done: bool
    info: any

    @staticmethod
    def unbatch(step: Step) -> list[Step]:
        return [
            Step(
                obs=step.obs[i:i+1],
                next_obs=step.next_obs[i:i+1],
                action=step.action[i:i+1],
                reward=step.reward[i:i+1],
                done=step.done,
                info=step.info[i:i+1],
            )
            for i in range(step.obs.shape[0])
        ]

    @staticmethod
    def batch(steps: list[Step]) -> Step:
        return Step(
            obs=np.concatenate([step.obs for step in steps], axis=0),
            next_obs=np.concatenate([step.next_obs for step in steps], axis=0),
            action=np.concatenate([step.action for step in steps], axis=0),
            reward=np.concatenate([step.reward for step in steps], axis=0),
            done=any(step.done for step in steps),
            info=[step.info for step in steps])

    @staticmethod
    def from_no_batch_axis(step: NoBatchStep) -> Step:
        return Step(
            obs=step.obs[None, ...],
            next_obs=step.next_obs[None, ...],
            action=step.action[None, ...],
            reward=step.reward[None, ...],
            done=step.done,
            info=[step.info]
        )

# dimensional type hinting
BatchStep = Step
NoBatchStep = Step

Traj = list[BatchStep]

In [35]:
class Environment:
    """RL environment."""

    def __init__(self):
        pass

    def reset(self) -> Step:
        """Resets the environment

        Returns:
            Step: Initial step. The `next_obs` attribute should be set 
                with an initial observation. `done` should be False. 
                `obs` and `action` should not be used.
        """
        pass

    def step(self, action: int) -> Step:
        """Computes one logical step in the environment

        Args:
            action (int): The action to take.

        Returns:
            Step: Step resulting from taking `action`. The `next_obs` attribute
                should be set with the observation resulting from taking the `action`
                in the current environment state. `obs` should not be used. If the 
                environment is turn-based, then the reward should correspond to the 
                agent that just acted (not the next agent in line to act).
        """
        pass

    def render(self):
        pass


class NoBatchEnv(Environment):
    """Environment with no batch dimension."""

    def reset(self) -> NoBatchStep:
        pass

    def step(self, action: int) -> NoBatchStep:
        pass


class BatchEnv(Environment):
    """Environment with batch dimension."""

    def reset(self) -> BatchStep:
        pass

    def step(self, action: np.ndarray) -> BatchStep:
        pass


In [23]:
class Batch1Env(BatchEnv):
    """Adds a batch axis to all outgoing Steps and strips it off incoming Steps."""

    def __init__(self, env: NoBatchEnv):
        self.env = env

    def reset(self) -> BatchStep:
        return Step.from_no_batch_axis(self.env.reset())

    def step(self, action: np.array) -> BatchStep:
        return Step.from_no_batch_axis(self.env.step(action[0]))

    def render(self):
        self.env.render()

In [18]:
class ParallelEnv(BatchEnv):
    """Keeps reseting the same environment in a batch.
    
    Declares itself done when a total of `batch_size` individual environment
    dones are experienced.

    NOTE: Individual environments should be `NoBatchEnv`'s.
    """

    def __init__(self, batch_size: int, env_init_fn: Callable[[], NoBatchEnv]):
        self.batch_size = batch_size
        self.env_init_fn = env_init_fn

    def reset(self) -> Step:
        self.dones = 0
        self.envs = [self.env_init_fn() for _ in range(self.batch_size)]
        steps = [env.reset() for env in self.envs]
        steps = [Step.from_no_batch_axis(step) for step in steps]
        return Step.batch(steps)

    def step(self, action: np.array) -> Step:
        steps = []
        for i, (env, single_action) in enumerate(zip(self.envs, action)):
            step = env.step(single_action)
            if step.done:
                self.envs[i] = self.env_init_fn()
                new_step = env.reset()
                step.next_obs = new_step.next_obs
                self.dones += 1
            steps.append(Step.from_no_batch_axis(step))

        batched_step = Step.batch(steps)
        batched_step.done = self.dones >= self.batch_size
        return batched_step

    def render(self):
        for env in self.envs:
            env.render()

In [37]:
class ReplayBuffer:
    """Replay buffer.

    Expects the following hyperparameters:
        - `epoch`: The current epoch.
        - `batch_size`: Number of trajectories to return at each call.
        - `min_sample_len`: Minimum length of trajectories to sample.
        - `max_sample_len`: Maximum length of trajectories to sample.
        - `num_steps_replay_coef`: Sampling coefficient based on trajectory length.
        - `success_replay_coef`: Sampling coefficient based on trajectory success.
        - `age_replay_coef`: Sampling coefficient based on trajectory age.
    """
  
    def __init__(self, hparams: dict):
        self.hparams = hparams
        self.trajs = dict()

    @property
    def flat_traj(self):
        return [step for traj in self.trajs for step in traj]

    def add(self, traj: Traj, epoch: int):
        """Add a new trajectory to the buffer.

        Args:
            traj (Traj): the trajectory to add.
            epoch (int): the epoch that the trajectory was experience in.
        """
        if epoch not in self.trajs:
            self.trajs[epoch] = []
        self.trajs[epoch] += traj

    def sample(self) -> Traj:
        """Samples a batched trajectory from the buffer stochastically based on:
            - the number of steps in the trajectory (num_steps_replay_coef)
            - how well the agent did in the trajectory (success_replay_coef)
            - how long ago the trajectory was experienced (age_replay_coef)

        Returns:
            Traj: a trajectory of batched steps experienced.
        """
        
        weights = {
            epoch: self.hparams['num_steps_replay_coef'] * len(traj) +
                   self.hparams['success_replay_coef'] * sum(step.reward for step in traj) +
                   self.hparams['age_replay_coef'] * (epoch - self.hparams['epoch'])
            for epoch, traj in self.trajs.items()
        }
        epochs = np.random.choice(list(weights.keys()), size=(), replace=True, p=list(weights.values()))
        trajs = [self.trajs[epoch] for epoch in epochs]
        batched_traj = [BatchStep.batch(steps) for steps in zip(*trajs)]
        return batched_traj

In [34]:
class Agent:

    def __init__(self, policy: Callable):
        self.policy = policy

    def forward(self, step: BatchStep) -> np.ndarray:
        """Generates an action for a given observation using `self.policy`. 
        Override if you want to give your policy more information such as
        recurrent state or previous reward.

        Args:
            step (Step): last step output by the environment. This means the agent
                should feed `step.next_obs`, not `step.obs` to its policy. If the 
                environment is multi-agent, then the `reward` attribute has already
                updated to reflect the reward for this agent by the driver.

        Returns:
            np.ndarray: The action to take
        """
        return self.policy(step.next_obs)

    def reward(self, traj: Traj) -> float:
        """Evaluates the cumulative reward for your agent as the sum of 
        individual rewards experienced. 
        
        If your agent uses intrinsic rewards, be sure to add them in here.
        Do not introduce Q-values or predicted rewards here.

        Args:
            traj (Traj): timestep trajectory.

        Returns:
            float: Cumulative (sum) reward over the entire sequence.
        """
        return sum(step.reward for step in traj)

    def train(self, traj: Traj):
        """Train your agent on a sequence of Timestep's.

        Args:
            traj (Traj): timestep trajectory.
        """
        raise NotImplemented('Method `train` must be implemented by subclass')

In [1]:
class ParallelDriver:
    """Drives batched turn-based `BatchedEnv` environments with multiple agents.
    Also supports single-agent environments as a special case.
    """

    def __init__(self):
        pass

    def drive(self, agents: dict[str, Agent], env: Environment) -> dict[str, Traj]:
        """Drives a batched environment with multiple agents.
        
        Args:
            agents (dict[str, Agent]): A dictionary of agents to drive.
            env (Environment): The environment to drive.

        Returns:
            dict[str, Traj]: A dictionary of trajectories for each agent.
                Each trajectory is completely disengaged from the other agent's.
                (i.e.: the obs, next_obs, action, reward, done attributes are
                individual to each agent for each trajectory.)
        """

        names_it = itertools.cycle(agents.keys())
        trajs = {agent_name: [] for agent_name in agents}
        prev_rewards = {agent_name: 0. for agent_name in agents}

        step = env.reset()
        while not step.done:
            agent_name = next(names_it)
            
            # `Agent.forward` only looks at `step.next_obs` and `step.reward`
            # but I'm assigning defaults just to be safe.
            action = agents[agent_name].forward(Step(
                obs=step.obs,  # what the previous agent saw before acting
                next_obs=step.next_obs,  # what the current agent sees before acting
                reward=prev_rewards[agent_name],  # the reward this agent experienced following its last action
                done=step.done,  # whether the environment was done after the previous agent acted
                info=step.info  # any extra information the environment might have output
            )) 

            prev_step = step
            step = env.step(action)  # `Environment.step` produces a Step with all fields except `step.obs` set
            step.obs = prev_step.next_obs  # the current agent's observation is the previous agent's next observation
            prev_rewards[agent_name] = step.reward  # the reward for the action the current agent just took
            trajs[agent_name].append(step)  # Step completely corresponding to this agent (obs before action, obs after action, action, reward, done, info)
        
        return trajs

NameError: name 'Agent' is not defined

In [38]:
class ParallelTrainer:
    """Trains `BatchedEnv` environments and mutliple agents 
    (with N=1 single-agent supported as a special case).
    
    Uses following hyperparameters:
    - `epoch`: the current epoch. Reads and writes to this variable.
    - `epochs`: the number of epochs to train for.
    - `min_steps_per_epoch`: the minimum number of steps to train for each epoch.
    """

    def __init__(self, hparams: dict, callbacks: list[Callable]):
        self.hparams = hparams
        self.callbacks = callbacks
        
    def train(self, 
        agents: dict[str, Agent], 
        env: Environment,
        test_env: Environment = None,
        buffers: dict[str, ReplayBuffer] = None,
        collect_driver: ParallelDriver = None,
        test_driver: ParallelDriver = None,
        histories: dict[str, dict[int, dict[str, any]]] = None,
        ) -> dict[int, dict[str, any]]:

        agent_names = list(agents.keys())
        
        # initialize defaults
        if test_env is None:
            test_env = env
        if buffers is None:
            buffers = dict()
        if collect_driver is None:
            collect_driver = ParallelDriver()
        if test_driver is None:
            test_driver = collect_driver
        if histories is None:
            histories = dict()  # {agent_name: {epoch: {...data}}}

        # build uninitialized agent-specific objects
        for agent_name in agent_names:
            if agent_name not in buffers:
                buffers[agent_name] = ReplayBuffer()
            if agent_name not in histories:
                histories[agent_name] = dict()

        # run training loop
        for epoch in range(self.hparams['epoch'], self.hparams['epochs']):
            self.hparams['epoch'] = epoch

            # collect trajectories
            steps = 0
            while steps < self.hparams['steps_per_epoch']:
                collect_trajs = collect_driver.drive(agents, env)
                steps += min(len(traj) for _, traj in collect_trajs.items())
                for agent_name in agent_names:
                    buffers[agent_name].add(collect_trajs[agent_name])

            # train
            train_trajs = {agent_name: buffers[agent_name].sample() for agent_name in agent_names}
            for agent_name in agent_names:
                agents[agent_name].train(train_trajs[agent_name])
                
            # test
            test_trajs = test_driver.drive(agents, env)

            # record history and run callbacks
            for agent_name in agent_names:
                histories[agent_name][epoch] = {
                    'epoch': epoch,
                    'agent': agents[agent_name],
                    'all_agents': agents,
                    'env': env,
                    'test_env': test_env,
                    'collect_traj': collect_trajs[agent_name],
                    'train_traj': train_trajs[agent_name],
                    'test_traj': test_trajs[agent_name],
                    'buffer': buffers[agent_name],
                }
                for callback in self.callbacks:
                    callback(histories[agent_name][epoch])

        return histories

In [40]:
class PrintCallback:

    def __init__(self, hparams: dict, print_hparam_keys: list[str] = None, print_data_keys: list[str] = None):
        if print_hparam_keys is None:
            print_hparam_keys = ['epoch']
        if print_data_keys is None:
            print_data_keys = []
        
        self.hparams = hparams
        self.print_hparam_keys = print_hparam_keys
        self.print_data_keys = print_data_keys

    def __call__(self, data: dict[str, any]):
        for key in self.print_hparam_keys:
            print(f'{key}: {self.hparams[key]}', end='\t')
        for key in self.print_data_keys:
            print(f'{key}: {data[key]}', end='\t')

In [2]:
class QEvalCallback:

    def __init__(self, 
        eval_on_collect: bool = True, 
        eval_on_train: bool = False, 
        eval_on_test: bool = False):

        self.eval_on_collect = eval_on_collect
        self.eval_on_train = eval_on_train
        self.eval_on_test = eval_on_test

    def __call__(self, data: dict[str, any]):
        agent = data['agent']
        if not hasattr(agent, 'q_eval'):
            return

        if self.eval_on_collect:
            traj = data['collect_traj']
            q_val = agent.q_eval(traj)
            data['q_collect'] = q_val

        if self.eval_on_train:
            traj = data['train_traj']
            q_val = agent.q_eval(traj)
            data['q_train'] = q_val

        if self.eval_on_test:
            traj = data['test_traj']
            q_val = agent.q_eval(traj)
            data['q_test'] = q_val

TypeError: 'type' object is not subscriptable

TODO
- make the reward optionally an advantage computation over last round
- also make a recurrent DQN agent (estimate q function of a sequence of states)
- make a simple greedy connect4 agent
- make the preprocessor perform a columnwise mean pool before flattening
- train the preprocessor on an auxillary objective to estimate the max connected for each length for self and for oponent
- add padding='SAME'|'VALID' to conv2d

### Agent implementations

In [16]:
class RandomAgent(Agent):
    """Takes a random action on each timestep."""

    def __init__(self, num_actions: int):
        self.policy = lambda obs : np.random.randint(0, num_actions, (obs.shape[0],))

    def train(self, traj: Traj):
        """Train your agent on a sequence of Timestep's.

        Args:
            traj (Traj): timestep trajectory.
        """
        pass

In [17]:
class RealDQN(Agent):
    """'Classic' Deep Q-learning agent.
    Implements the approach in https://arxiv.org/pdf/1312.5602.pdf.
    """

    def __init__(self, num_actions: int, encoder: Layer, hparams: dict):

        self.num_actions = num_actions
        self.encoder = encoder
        self.head = Sequential([
            Dense(512, Sigm), 
            Dense(1, lambda x: x)
        ]) # [B, L+|A|] -> [B, 1]
        self.hparams = hparams

        super(RealDQN, self).__init__(policy=self._policy)

    def _policy(self, obs: np.ndarray) -> np.ndarray:

        # Maybe take greedy step
        epsilon = self.hparams['epsilon_start'] * self.hparams['epsilon_decay']**self.hparams['epoch']
        epsilon = min(epsilon, self.hparams['min_epsilon'])
        if random.random() < epsilon:
            return np.random.rand(self.num_actions)
        
        # Otherwise take the action with the highest Q-value
        actions = np.arange(self.num_actions)  # [self.num_actions]
        q_vals = np.zeros((self.num_actions,))  # [self.num_actions]
        for i, action in enumerate(actions):
            
            # prepare inputs
            obs_T = Var(obs[None, ...])  # [1, H, W, 2]
            action_T = Var(action[None, None], trainable=False)  # [1, 1]

            # run the network
            enc_T = self.encoder(obs_T)  # [1, d_enc]
            cat_T = Concat([enc_T, action_T], axis=1)  # [1, d_enc+1]
            q_T = self.head(cat_T)  # [1, 1]

            # store q-value
            q_vals[i] = q_T.val[0,0]  # []
        
        # select the action with the highest Q-value
        action = actions[q_vals.argmax()]
        return action

    def train(self, traj: Traj):
        """Train your agent on a sequence of Timestep's.

        Args:
            traj (Traj): batched timestep trajectory.
        """

        optimizer = self.hparams['optimizer']
        discount_T = Var(self.hparams['discount'], trainable=False)  # []
        for step in traj:

            obs_T = Var(step.obs, trainable=False)  # [B, H, W, 2]
            action_T = Var(step.action[None], trainable=False)  # [B, 1]
            action_next_T = Var(self.policy(step.next_obs), trainable=False)  # [B, 1]
            r_T = Var(step.reward, trainable=False)  # [B]

            # compute previous Q value using the actual (not necesarily optimal) action selected
            enc_T = self.encoder(obs_T)  # [B, d_enc]
            cat_T = Concat([enc_T, action_T], axis=1)  # [B, d_enc+1]
            Qnow_T = self.head(cat_T)[:, 0]  # [B]
            reg_loss_now_T = self.encoder.loss + self.head.loss  # []

            # compute the maximum possible next step Q-value
            enc_T = self.encoder(obs_T)  # [B, d_enc]
            cat_T = Concat([enc_T, action_next_T], axis=1)  # [B, d_enc+1]
            Qnext_T = self.head(cat_T)[:, 0]  # [B]
            reg_loss_next_T = self.encoder.loss + self.head.loss  # []

            # train the current policy to estimate new Q-value 
            # i.e.: approx Qnew_T <= (1-lr)*Qnow_T + lr*(r_T+discount_T*Qnext_T)  # [B, 1]
            # using gradient descent (let lr=1 in the above; small updates are handled in the SGD step)
            loss_T = ReduceSum(((r_T+discount_T*StopGrad(Qnext_T)) - Qnow_T)**2,
                axis=0) + reg_loss_now_T + reg_loss_next_T  # []
            optimizer.minimize(loss_T)

    def q_eval(self, obs: np.ndarray, action: np.ndarray) -> np.ndarray:
        """Evaluate the Q-value of a given state-action pair.

        Args:
            obs (np.ndarray): observation.
            action (np.ndarray): action.

        Returns:
            q_val (np.ndarray): Q-value of the given state-action pair.
        """

        # prepare inputs
        obs_T = Var(obs)  # [B, H, W, 2]
        action_T = Var(action)  # [B, 1]
        enc_T = self.encoder(obs_T)  # [B, d_enc]
        cat_T = Concat([enc_T, action_T], axis=1)  # [B, d_enc+1]
        Qnow_T = self.head(cat_T)[:, 0]  # [B]

        return Qnow_T.val


encoder = Sequential([
    Conv2D(32, 3, 2, 'same', Relu),
    Conv2D(64, 3, 2, 'same', Relu),
    Flatten(),
])  # [B, H, W, 1] -> [B, L]

agent = RealDQN(num_actions=HPARAMS['board_size'], encoder=encoder, hparams=HPARAMS)
agent

NameError: name 'HPARAMS' is not defined

In [ ]:
class CategoricalDQN(Agent):
    """Categorical deep Q-network agent.
    I never read the paper for this architecture, so my implementation
    might be different from the origonal researchers.
    """

    def __init__(self, num_actions: int, encoder: Layer, hparams: dict):

        self.num_actions = num_actions
        self.encoder = encoder  # [B, H, W, C] -> [B, d_enc]
        self.head = Sequential([
            Dense(2*hparams['board_size']*num_actions, Tanh),
            Dense(num_actions, Linear)
        ]) # [B, d_enc] -> [B, num_actions]
        self.hparams = hparams

        super(CategoricalDQN, self).__init__(policy=self._policy)

    def _policy(self, obs: np.ndarray) -> np.ndarray:

        # Maybe take greedy step
        epsilon = self.hparams['epsilon_start'] * self.hparams['epsilon_decay']**self.hparams['epoch']
        epsilon = min(epsilon, self.hparams['min_epsilon'])
        if random.random() < epsilon:
            return np.random.rand(self.num_actions)
        
        # Otherwise take the action with the highest Q-value
        # compute q-values for all actions
        obs_T = Var(obs, trainable=False)  # [B, H, W, C]
        enc_T = self.encoder(obs_T)  # [B, d_enc]
        qvals_T = self.head(enc_T)  # [B, A]
        return np.argmax(qvals_T.val, axis=1)  # [B]

    
    def train(self, traj: Traj):
        """Train your agent on a sequence of Timestep's.

        Args:
            traj (Traj): batched timestep trajectory.
        """

        optimizer = self.hparams['optimizer']
        discount_T = Var(self.hparams['discount'], trainable=False)  # []
        for step in traj:

            obs_T = Var(step.obs, trainable=False)  # [B, H, W, 2]
            obs_next_T = Var(step.next_obs, trainable=False)  # [B, H, W, 2]
            r_T = Var(step.reward, trainable=False)  # [B]

            # compute previous Q value using the actual (not necesarily optimal) action selected
            enc_T = self.encoder(obs_T)  # [B, d_enc]
            qvals_T = self.head(enc_T)  # [B, A]
            Q_now_T = qvals_T[step.action]  # [B]
            reg_loss_now_T = self.encoder.loss + self.head.loss  # []

            # compute the maximum possible next step Q-value
            enc_T = self.encoder(obs_next_T)  # [B, d_enc]
            qvals_T = self.head(enc_T)  # [B, A]
            Q_next_T = np.max(qvals_T.val, axis=1)  # [B]
            reg_loss_next_T = self.encoder.loss + self.head.loss  # []

            # train the current policy to estimate new Q-value 
            # i.e.: approx Qnew_T <= (1-lr)*Qnow_T + lr*(r_T+discount_T*Qnext_T)  # [B, 1]
            # using gradient descent (let lr=1 in the above; small updates are handled in the SGD step)
            # but only update the targets that were actually selected for action at `step_now`.
            loss_T = ReduceSum(((r_T+discount_T*StopGrad(Q_next_T)) - Q_now_T)**2,
                axis=0) + reg_loss_now_T + reg_loss_next_T  # []
            optimizer.minimize(loss_T)


    def q_eval(self, obs: np.ndarray, action: np.ndarray) -> np.ndarray:
        """Evaluate the Q-value of a given state-action pair.

        Args:
            obs (np.ndarray): observation.
            action (np.ndarray): action.

        Returns:
            q_val (np.ndarray): Q-value of the given state-action pair.
        """

        # prepare inputs
        obs_T = Var(obs)  # [B, H, W, 2]
        enc_T = self.encoder(obs_T)  # [B, d_enc]
        qvals_T = self.head(enc_T)  # [B, A]

        return qvals_T.val[action]


agent = CategoricalDQN(num_actions=HPARAMS['board_size'], encoder=encoder, hparams=HPARAMS)
agent

## Connect 4

In [ ]:
class HardwiredConnect4Agent(Agent):

    def __init__(self, board_size: int, hparams: dict):
        self.board_size = board_size
        self.hparams = hparams
        super(HardwiredConnect4Agent, self).__init__(policy=self._policy)

    def _policy(self, obs: np.ndarray) -> np.ndarray:
        B = obs.shape[0]
        action = np.zeros(B, dtype=np.int32)
        for b in range(B):
            o = obs[b]
            ## TODO: make a greedy agent
            action[b] = random.randint(0, self.board_size-1)
        return action

    def train(self, traj: Traj):
        pass

In [ ]:
class Board:
    """Drafted by copilot with minor human edits"""

    def __init__(self, size=7, win_length=4):
        self.size = size
        self.win_length = win_length
        self.board = np.zeros((size, size))
        self.turn = 1
        self.winner = 0

    def __str__(self):
        return f'{self.board}\nTurn: {self.turn}\nWinner: {self.winner}'

    def __repr__(self):
        return self.__str__()

    def __eq__(self, other):
        return self.board == other.board

    def __hash__(self):
        return hash(self.board.tostring())

    def is_full(self):
        return np.count_nonzero(self.board) == self.size**2

    def is_empty(self, col):
        return self.board[0, col] == 0

    def is_valid_move(self, col):
        return 0 <= col < self.size and self.is_empty(col)

    def make_move(self, col):
        if self.is_valid_move(col):
            highest_row = np.where(self.board[:, col] == 0)[0][-1]
            self.board[highest_row, col] = self.turn
            self.turn *= -1

    def undo_move(self, col):
        if self.is_valid_move(col) and self.board[0, col] != 0:
            highest_row = np.where(self.board[:, col] == 0)[0][-2]
            self.board[highest_row, col] = 0
            self.turn *= -1

    def check_win(self) -> int:
        for turn in [-1, 1]:
            if self.num_connected(self.win_length, turn) > 0:
                self.winner = turn
                return True
        return self.winner

    def num_connected(self, length, turn):
        num_connected = 0
        # Check horizontal
        for row in range(self.size):
            for col in range(self.size-length+1):
                if np.all(self.board[row, col:col+length] == turn):
                    num_connected += 1
        # Check vertical
        for col in range(self.size):
            for row in range(self.size-length+1):
                if np.all(self.board[row:row+length, col] == turn):
                    num_connected += 1
        # Check diagonal
        for row in range(self.size-length+1):
            for col in range(self.size-length+1):
                if all(self.board[row+i, col+i] == turn for i in range(length)):
                    num_connected += 1
        # Check anti-diagonal
        for row in range(self.size-length+1):
            for col in range(length-1, self.size):
                if all(self.board[row+i, col-i] == turn for i in range(length)):
                    num_connected += 1
        return num_connected

board = Board()
board.make_move(0)
board.make_move(0)
board.make_move(0)
board.make_move(0)
board

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]]
Turn: 1
Winner: 0

In [ ]:
class BoardEnv:

    def __init__(self, board_size=7, win_length=4, sparse_reward=False):
        self.board_size = board_size
        self.win_length = win_length
        self.sparse_reward = sparse_reward

        self.reset()

    def reset(self):
        self.board = Board(self.board_size, self.win_length)

        return self.board.board

    def step(self, action: int):
        """Apply agent X's action to the board and 
        returns the next agent's timestep.

        Args:
            action (int): integer in [0, board_size)

        Returns:
            tuple: NoBatchStep with values:
                obs (np.ndarray[H, W, 2]): 0's tensor (`None` substitute)
                next_obs (np.ndarray[H, W, 2]): the next board state with
                    self's entered squares represented in channel 0 and
                    opponent's squares represented in channel 1
                reward (float): the reward for the agent
                    If sparse_reward is True, then reward is -1, 0, or +1.
                    If sparse_reward is False, then reward is:
                        ego_dense_reward - opponent_dense_reward.
                done (bool): whether the game is over
                info (dict): extra information
        """
        # Apply action
        self.board.make_move(action)  # this flips `board.turn`

        # Make egocentric observation
        obs = (self.board.turn * self.board.board)[..., None]  # [H, W, 1]

        # Compute reward
        if self.sparse_reward:
            winner = self.board.check_win()
            reward = self.board.turn * winner
        else:
            def dense_reward(board, turn):
                r = 0
                for length in range(2, self.board_size):
                    r += math.log(length) * board.num_connected(length, turn)
                return r
            ego_dense_reward = dense_reward(self.board, self.board.turn)
            opponent_dense_reward = dense_reward(self.board, -self.board.turn)
            reward = ego_dense_reward - opponent_dense_reward

        # Evaluate whether game is over
        winner = self.board.check_win()
        done = winner != 0

        # Record debugging info
        info = dict()

        return NoBatchStep(
            obs=np.zeros_like(obs),
            next_obs=obs, 
            reward=reward, 
            done=done, 
            info=info
        )

    def render(self):
        print(self.board)

board_size = 10
env = BoardEnv(board_size=board_size, win_length=5, sparse_reward=False)
obs = env.reset()

done = False
while not done:
    action = random.randint(0, board_size-1)
    obs, reward, done, info = env.step(action)

    print(f'Action: {action}')
    env.render()
    print(f'Reward: {reward}\n')

print(f'Winner: {env.board.winner}')

Action: 9
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Turn: -1
Winner: 0
Reward: 0.0

Action: 3
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  1.]]
Turn: 1
Winner: 0
Reward: 0.0

Action: 9
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0

In [ ]:
INITIAL_HPARAMS = dict(
    board_size=8,           # Board size
    discount=0.99,          # Discount factor
    learning_rate=0.001,    # Learning rate
    batch_size=32,          # Number of samples per training batch
    train_freq=10000,       # Number of timesteps between training steps
    epoch=0,                # Current epoch
    epochs=10,              # Number of training epochs
    epsilon_start=1.0,      # Starting value for epsilon
    min_epsilon=0.01,       # Final value for epsilon
    epsilon_decay=0.95,     # Decay rate for epsilon per epoch
)

INITIAL_HPARAMS['optimizer'] = \
    SGD(INITIAL_HPARAMS['learning_rate'])   # Optimizer


HPARAMS = INITIAL_HPARAMS.copy()